# Generated by Django 6.1.1 on 2026-10-10 13:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modificato il"),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="revisione"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="denominazione"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("public_body", "Ente pubblico"),
                            ("public_company", "Azienda pubblica"),
                            ("condominium", "Condominio"),
                            ("company", "Azienda"),
                            ("private", "Privato"),
                            ("other", "Altro"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "istat_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{5,6}$",
                                code="invalid_istat_code",
                                message="The ISTAT code has 5 or 6 digits.",
                            )
                        ],
                        verbose_name="codice ISTAT del comune",
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=16,
                        verbose_name="codice fiscale o partita IVA",
                    ),
                ),
                (
                    "contacts",
                    models.TextField(blank=True, default="", verbose_name="recapiti"),
                ),
                (
                    "cam_export_srid",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (6706, "RDN2008 geografico (EPSG:6706)"),
                            (7791, "RDN2008 / UTM 32N (EPSG:7791)"),
                            (7792, "RDN2008 / UTM 33N (EPSG:7792)"),
                            (7793, "RDN2008 / UTM 34N (EPSG:7793)"),
                            (7794, "RDN2008 / Italy zone (EPSG:7794)"),
                        ],
                        null=True,
                        verbose_name="sistema di riferimento per l'export CAM",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="attivo")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="note"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "managing_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_clients",
                        to="tenants.tenant",
                        verbose_name="organizzazione di gestione",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "committente",
                "verbose_name_plural": "committenti",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["managing_organization", "active"],
                        name="parties_client_org_idx",
                    )
                ],
            },
        ),
    ]
