export const AUTH_CORE_PERMISSIONS = {
  LETTURA_UTENTI: "auth_core.LETTURA_UTENTI",
  SCRITTURA_UTENTI: "auth_core.SCRITTURA_UTENTI",
  LETTURA_RUOLI: "auth_core.LETTURA_RUOLI",
  SCRITTURA_RUOLI: "auth_core.SCRITTURA_RUOLI",
} as const
