# Generated by Django 6.1.1 on 2026-10-10 13:30

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity", models.CharField(max_length=100, verbose_name="entità")),
                ("record_id", models.UUIDField(verbose_name="record")),
                (
                    "client_id",
                    models.UUIDField(blank=True, null=True, verbose_name="committente"),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Creazione"),
                            ("update", "Modifica"),
                            ("cancel", "Annullamento"),
                        ],
                        max_length=20,
                        verbose_name="operazione",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="modifiche",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="", verbose_name="motivazione"
                    ),
                ),
                (
                    "author_label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="nome dell'autore"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="registrata il"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("field", "Campo"),
                            ("import", "Import"),
                            ("sync", "Sincronizzazione"),
                            ("system", "Sistema"),
                        ],
                        max_length=20,
                        verbose_name="origine",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autore",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_records",
                        to="tenants.tenant",
                        verbose_name="organizzazione",
                    ),
                ),
            ],
            options={
                "verbose_name": "modifica",
                "verbose_name_plural": "storico delle modifiche",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "record_id"], name="core_change_record_idx"
                    ),
                    models.Index(
                        fields=["client_id", "recorded_at"],
                        name="core_change_client_idx",
                    ),
                    models.Index(
                        fields=["organization", "recorded_at"],
                        name="core_change_org_idx",
                    ),
                ],
            },
        ),
    ]
