# Generated by Django 6.1.1 on 2026-10-10 07:27

from django.db import migrations

# Codes of data-lab, in Italian, renamed to English (D-001).
RENAMED = {
    "auth_core.LETTURA_UTENTI": "auth_core.READ_USERS",
    "auth_core.SCRITTURA_UTENTI": "auth_core.WRITE_USERS",
    "auth_core.LETTURA_RUOLI": "auth_core.READ_ROLES",
    "auth_core.SCRITTURA_RUOLI": "auth_core.WRITE_ROLES",
}


def rename(codes, mapping):
    return [mapping.get(code, code) for code in codes]


def rename_codes(apps, mapping):
    Role = apps.get_model("auth_core", "Role")
    User = apps.get_model("auth_core", "User")
    for role in Role.objects.all():
        role.permissions = rename(role.permissions, mapping)
        role.save(update_fields=["permissions"])
    for user in User.objects.all():
        user.permissions = rename(user.permissions, mapping)
        user.all_permissions = rename(user.all_permissions, mapping)
        user.save(update_fields=["permissions", "all_permissions"])


def forwards(apps, schema_editor):
    rename_codes(apps, RENAMED)


def backwards(apps, schema_editor):
    rename_codes(apps, {new: old for old, new in RENAMED.items()})


class Migration(migrations.Migration):

    dependencies = [
        ("auth_core", "0002_initial"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
