# Generated by Django 6.1.1 on 2026-10-10 13:30

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modificato il"),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="revisione"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Codice stabile, usato da import, export e dati iniziali.",
                        max_length=150,
                        verbose_name="codice",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descrizione"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="ordine")),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="fonte"
                    ),
                ),
                (
                    "retired",
                    models.BooleanField(
                        default=False,
                        help_text="Non si sceglie più, ma resta valida sui dati che la usano.",
                        verbose_name="ritirata",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("number", "Numero"),
                            ("text", "Testo"),
                            ("boolean", "Sì/no"),
                            ("choice", "Scelta"),
                            ("date", "Data"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="unità"
                    ),
                ),
                (
                    "choices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        verbose_name="valori ammessi",
                    ),
                ),
                (
                    "is_measure",
                    models.BooleanField(
                        default=False,
                        help_text="Varia nel tempo e si registra nelle osservazioni.",
                        verbose_name="misura",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "hidden_by",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Organizzazioni che nascondono la voce di sistema.",
                        related_name="+",
                        to="tenants.tenant",
                        verbose_name="nascosta da",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vuota per le voci di sistema.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="organizzazione",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "attributo",
                "verbose_name_plural": "attributi",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ElementClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modificato il"),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="revisione"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Codice stabile, usato da import, export e dati iniziali.",
                        max_length=150,
                        verbose_name="codice",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descrizione"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="ordine")),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="fonte"
                    ),
                ),
                (
                    "retired",
                    models.BooleanField(
                        default=False,
                        help_text="Non si sceglie più, ma resta valida sui dati che la usano.",
                        verbose_name="ritirata",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vegetation", "Vegetazione"),
                            ("furniture", "Arredo"),
                            ("play", "Gioco"),
                            ("facility", "Impianto"),
                            ("other", "Altro"),
                        ],
                        max_length=20,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "geometry_type",
                    models.CharField(
                        choices=[
                            ("point", "Punto"),
                            ("line", "Linea"),
                            ("polygon", "Poligono"),
                        ],
                        max_length=20,
                        verbose_name="tipo di geometria",
                    ),
                ),
                (
                    "quantity_unit",
                    models.CharField(
                        choices=[
                            ("count", "Numero"),
                            ("meter", "Metro"),
                            ("square_meter", "Metro quadro"),
                        ],
                        max_length=20,
                        verbose_name="unità di misura",
                    ),
                ),
                (
                    "species_mode",
                    models.CharField(
                        choices=[
                            ("none", "Nessuna"),
                            ("single", "Singola"),
                            ("composition", "Composizione"),
                            ("single_or_composition", "Singola o composizione"),
                        ],
                        max_length=30,
                        verbose_name="specie",
                    ),
                ),
                (
                    "counts_as_tree",
                    models.BooleanField(
                        default=False, verbose_name="conta come albero"
                    ),
                ),
                (
                    "is_planting_site",
                    models.BooleanField(default=False, verbose_name="posto d'impianto"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "hidden_by",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Organizzazioni che nascondono la voce di sistema.",
                        related_name="+",
                        to="tenants.tenant",
                        verbose_name="nascosta da",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vuota per le voci di sistema.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="organizzazione",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "classe di elemento",
                "verbose_name_plural": "classi di elemento",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ElementClassAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modificato il"),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="revisione"
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="obbligatorio"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="ordine")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_links",
                        to="catalogs.attributedefinition",
                        verbose_name="attributo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "element_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_attributes",
                        to="catalogs.elementclass",
                        verbose_name="classe di elemento",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "attributo della classe",
                "verbose_name_plural": "attributi delle classi",
                "ordering": ["sort_order", "attribute__name"],
            },
        ),
        migrations.CreateModel(
            name="RemovalCause",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modificato il"),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="revisione"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Codice stabile, usato da import, export e dati iniziali.",
                        max_length=150,
                        verbose_name="codice",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descrizione"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="ordine")),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="fonte"
                    ),
                ),
                (
                    "retired",
                    models.BooleanField(
                        default=False,
                        help_text="Non si sceglie più, ma resta valida sui dati che la usano.",
                        verbose_name="ritirata",
                    ),
                ),
                (
                    "istat_cause",
                    models.CharField(
                        choices=[
                            ("fall_risk", "Rischio di caduta"),
                            ("weather_event", "Eventi atmosferici"),
                            ("other", "Altre cause"),
                        ],
                        max_length=20,
                        verbose_name="causa ISTAT",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "hidden_by",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Organizzazioni che nascondono la voce di sistema.",
                        related_name="+",
                        to="tenants.tenant",
                        verbose_name="nascosta da",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vuota per le voci di sistema.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="organizzazione",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "causa di rimozione",
                "verbose_name_plural": "cause di rimozione",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modificato il"),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="revisione"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Codice stabile, usato da import, export e dati iniziali.",
                        max_length=150,
                        verbose_name="codice",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descrizione"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="ordine")),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="fonte"
                    ),
                ),
                (
                    "retired",
                    models.BooleanField(
                        default=False,
                        help_text="Non si sceglie più, ma resta valida sui dati che la usano.",
                        verbose_name="ritirata",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("genus", "Genere"),
                            ("species", "Specie"),
                            ("hybrid", "Ibrido"),
                            ("cultivar", "Cultivar"),
                        ],
                        default="species",
                        max_length=20,
                        verbose_name="livello",
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(max_length=255, verbose_name="nome scientifico"),
                ),
                ("genus", models.CharField(max_length=100, verbose_name="genere")),
                (
                    "specific_epithet",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="epiteto specifico",
                    ),
                ),
                (
                    "infraspecific",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="rango infraspecifico",
                    ),
                ),
                (
                    "cultivar",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="cultivar"
                    ),
                ),
                (
                    "family",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="famiglia"
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="nome comune",
                    ),
                ),
                (
                    "synonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        verbose_name="sinonimi",
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="riferimento esterno",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "hidden_by",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Organizzazioni che nascondono la voce di sistema.",
                        related_name="+",
                        to="tenants.tenant",
                        verbose_name="nascosta da",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vuota per le voci di sistema.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="organizzazione",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalogs.species",
                        verbose_name="voce superiore",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "specie",
                "verbose_name_plural": "specie",
                "ordering": ["scientific_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UrbanGreenType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modificato il"),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="revisione"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Codice stabile, usato da import, export e dati iniziali.",
                        max_length=150,
                        verbose_name="codice",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descrizione"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="ordine")),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="fonte"
                    ),
                ),
                (
                    "retired",
                    models.BooleanField(
                        default=False,
                        help_text="Non si sceglie più, ma resta valida sui dati che la usano.",
                        verbose_name="ritirata",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipologia di verde urbano",
                "verbose_name_plural": "tipologie di verde urbano",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UsageIntensity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modificato il"),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="revisione"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Codice stabile, usato da import, export e dati iniziali.",
                        max_length=150,
                        verbose_name="codice",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descrizione"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="ordine")),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="fonte"
                    ),
                ),
                (
                    "retired",
                    models.BooleanField(
                        default=False,
                        help_text="Non si sceglie più, ma resta valida sui dati che la usano.",
                        verbose_name="ritirata",
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(default=0, verbose_name="rango"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "hidden_by",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Organizzazioni che nascondono la voce di sistema.",
                        related_name="+",
                        to="tenants.tenant",
                        verbose_name="nascosta da",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vuota per le voci di sistema.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="organizzazione",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "intensità di fruizione",
                "verbose_name_plural": "intensità di fruizione",
                "ordering": ["rank", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AreaUse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modificato il"),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="revisione"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Codice stabile, usato da import, export e dati iniziali.",
                        max_length=150,
                        verbose_name="codice",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="descrizione"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="ordine")),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="fonte"
                    ),
                ),
                (
                    "retired",
                    models.BooleanField(
                        default=False,
                        help_text="Non si sceglie più, ma resta valida sui dati che la usano.",
                        verbose_name="ritirata",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creato da",
                    ),
                ),
                (
                    "hidden_by",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Organizzazioni che nascondono la voce di sistema.",
                        related_name="+",
                        to="tenants.tenant",
                        verbose_name="nascosta da",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vuota per le voci di sistema.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                        verbose_name="organizzazione",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "destinazione d'uso",
                "verbose_name_plural": "destinazioni d'uso",
                "ordering": ["sort_order", "name"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "code"),
                        name="catalogs_areause_code_uniq",
                        nulls_distinct=False,
                        violation_error_code="catalog_code_not_unique",
                        violation_error_message="An entry with this code already exists.",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="attributedefinition",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"),
                name="catalogs_attributedefinition_code_uniq",
                nulls_distinct=False,
                violation_error_code="catalog_code_not_unique",
                violation_error_message="An entry with this code already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="elementclass",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"),
                name="catalogs_elementclass_code_uniq",
                nulls_distinct=False,
                violation_error_code="catalog_code_not_unique",
                violation_error_message="An entry with this code already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="elementclassattribute",
            constraint=models.UniqueConstraint(
                fields=("element_class", "attribute"),
                name="catalogs_class_attribute_uniq",
                violation_error_code="class_attribute_duplicated",
                violation_error_message="The attribute is already in the class.",
            ),
        ),
        migrations.AddConstraint(
            model_name="removalcause",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"),
                name="catalogs_removalcause_code_uniq",
                nulls_distinct=False,
                violation_error_code="catalog_code_not_unique",
                violation_error_message="An entry with this code already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="species",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"),
                name="catalogs_species_code_uniq",
                nulls_distinct=False,
                violation_error_code="catalog_code_not_unique",
                violation_error_message="An entry with this code already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="species",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("scientific_name"),
                models.F("organization"),
                name="catalogs_species_name_uniq",
                nulls_distinct=False,
                violation_error_code="species_name_not_unique",
                violation_error_message="An entry with this scientific name already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="urbangreentype",
            constraint=models.UniqueConstraint(
                fields=("code",),
                name="catalogs_urbangreentype_code_uniq",
                violation_error_code="catalog_code_not_unique",
                violation_error_message="An entry with this code already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="usageintensity",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"),
                name="catalogs_usageintensity_code_uniq",
                nulls_distinct=False,
                violation_error_code="catalog_code_not_unique",
                violation_error_message="An entry with this code already exists.",
            ),
        ),
    ]
