# Generated by Django 6.1.1 on 2026-10-10 21:10

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0002_system_entries"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="species",
            name="catalogs_species_name_uniq",
        ),
        migrations.AddConstraint(
            model_name="species",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("scientific_name"),
                models.F("organization"),
                condition=models.Q(("retired", False)),
                name="catalogs_species_name_uniq",
                nulls_distinct=False,
                violation_error_code="species_name_not_unique",
                violation_error_message="An entry with this scientific name already exists.",
            ),
        ),
    ]
