# Generated by Django 6.1.1 on 2026-10-09 13:39

import django.db.models.deletion
import jobs_core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CronJobDefinition",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("cron", models.CharField(max_length=255)),
                (
                    "func",
                    models.CharField(
                        max_length=255,
                        validators=[jobs_core.models.validate_is_schedulable],
                    ),
                ),
                ("args", models.JSONField(blank=True, default=list)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                ("repeat", models.IntegerField(blank=True, null=True)),
                ("result_ttl", models.IntegerField(blank=True, null=True)),
                ("ttl", models.IntegerField(blank=True, null=True)),
                ("queue_name", models.CharField(default="default", max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("use_local_timezone", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledJobDefinition",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("start_at", models.DateTimeField()),
                (
                    "func",
                    models.CharField(
                        max_length=255,
                        validators=[jobs_core.models.validate_is_schedulable],
                    ),
                ),
                ("args", models.JSONField(blank=True, default=list)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                ("result_ttl", models.IntegerField(blank=True, null=True)),
                ("ttl", models.IntegerField(blank=True, null=True)),
                ("queue_name", models.CharField(default="default", max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("func", models.CharField(max_length=255)),
                ("args", models.JSONField(blank=True, default=list)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_details", models.TextField(blank=True)),
                (
                    "cron_job_definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_runs",
                        to="jobs_core.cronjobdefinition",
                    ),
                ),
                (
                    "scheduled_job_definition",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_run",
                        to="jobs_core.scheduledjobdefinition",
                    ),
                ),
            ],
        ),
    ]
